### ISSUE TITLE
Allow additional items (roles, categories and channels)

### ISSUE THREAD

**Issue by vigenere23** [vigenere23/disma#21]
## Description

Add config options to allow additional items that are not listed in the config.

- Roles
- Categories
- Channels in categories
- Channels without categories

### Config

```yaml
roles
  items: # BREAKING : root config items are now objects instead of lists
    - name: xxx
    - ...
  extra_items:
    strategy: remove | keep # maybe also "overwrite" with default metadata in the future

categories:
  items:
    - name: xxx
      ...
      extra_channels: # specific to channels under this category only
        strategy: remove | keep
    - ...
  extra_items:
    strategy: remove | keep

channels:
  items:
    - name: xxx
    - ...
  extra_items:
    strategy: remove | keep
```
