### ISSUE TITLE
Support for members inclusion/exclusion

### ISSUE THREAD

**Issue by vigenere23** [vigenere23/disma#25]
## Context

Auto-inviting or mass-kicking members in Discord is a real pain, as there is no bulk or automatic way to do this.

## Ideas

Add a `members` config with the following schema:

```yaml
members:
  items:
    - h324h882h324 # To determine if usernames, slowflakes (ids) or handles
    - ...
  strict: bool = false # weither or not to automatically exclude/kick all other members
```

### Notes

- Every user in the `include` section should not be in the guild's ban list, as this will result in either an error or an undefined behavior.
- Explicit exclusions should be managed directly on Discord since they are rare.
